[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 1337
via_ir = false

[profile.ci]
fuzz = { runs = 256 }

[rpc_endpoints]
base = "https://mainnet.base.org"
base_sepolia = "https://sepolia.base.org"
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
base = { key = "${BASESCAN_API_KEY}" }
basescan = { key = "${BASESCAN_API_KEY}" }
mainnet = { key = "${ETHERSCAN_API_KEY}" }


